# Generated by Django 3.0.5 on 2020-06-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200603_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
    ]
